{% set name = "PythiaLabelGenerator" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pythialabelgenerator-{{ version }}.tar.gz
  sha256: c94e15f8ed1e5d25cc94bc6ab7abb56cabc185c39e6bc999ab04d03a60380bc2

build:
  entry_points:
    - label = labelgenerator.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pythiaphylopredictor >=2.0.0
    - regex
    - loguru
    - __unix

test:
  imports:
    - labelgenerator
    - labelgenerator.iqtree
    - labelgenerator.iqtree_parser
    - labelgenerator.label
    - labelgenerator.raxmlng
  commands:
    - pip check
    - label --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tschuelia/PythiaLabelGenerator
  summary: Command line tool to generate the ground-truth phylogenetic difficulty of MSAs
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschuelia
