{% set name = "PythiaLabelGenerator" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythialabelgenerator-{{ version }}.tar.gz
  sha256: 2469fb9f979eb89872f05c583e5ac4cd3d050cc33cae0e3802123dc751a7900f

build:
  entry_points:
    - label = labelgenerator.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pythiaphylopredictor >=2.0.0
    - regex
    - loguru
    - __unix

test:
  imports:
    - labelgenerator
    - labelgenerator.iqtree
    - labelgenerator.iqtree_parser
    - labelgenerator.label
    - labelgenerator.raxmlng
  commands:
    - pip check
    - label --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tschuelia/PythiaLabelGenerator
  summary: Command line tool to generate the ground-truth phylogenetic difficulty of MSAs
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschuelia
